# Generated by Django 4.0.4 on 2022-05-20 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post_deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdeployaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
