# Generated by Django 4.0.4 on 2022-11-07 16:19

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('post_deploy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDeployLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('import_name', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(default=None, null=True)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('has_error', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
