# Generated by Django 4.0.4 on 2022-11-07 16:19

from django.db import migrations


def library_to_id(key):
    from django.utils.module_loading import import_string

    module, method = key.split('.')
    class_path = '.'.join([module, 'post_deploy', method])
    assert import_string(class_path), "Classpath [%s] is not a function." % class_path
    return class_path


def populate_log(apps, schema_editor):
    # load post_deploy_actions
    PostDeployAction = apps.get_model('post_deploy', 'PostDeployAction')
    PostDeployLog = apps.get_model('post_deploy', 'PostDeployLog')

    print("at populate_log")
    print(PostDeployAction.objects.all())

    for action in PostDeployAction.objects.all():
        if action.completed_at:
            new_log = PostDeployLog.objects.create(
                import_name=library_to_id(action.id),
                created_at=action.started_at,
                completed_at=action.completed_at,
                task_id=action.task_id,
                message=action.message,
            )
            print(new_log)


class Migration(migrations.Migration):
    dependencies = [
        ('post_deploy', '0002_postdeploylog'),
    ]

    operations = [
        migrations.RunPython(populate_log, reverse_code=migrations.RunPython.noop)
    ]
